#!/bin/bash
echo -e "\033[1;36m ESTOS SON SUS DATOS!\033[0m"
echo ""
echo -ne "SU NS (Nameserver): " && cat /etc/slowdns/infons
echo ""
echo -ne "SU KEY: " && cat /root/server.pub
echo ""
echo -ne "\033[1;33mCOMANDO TERMUX:\033[0m curl -sO https://raw.githubusercontent.com/T3mma/script-with-bot/main/slowdns/slowdns && chmod +x slowdns && ./slowdns " && cat /etc/slowdns/infons /root/server.pub
echo ""
echo -e "\033[1;33m SU KEY está guardado en el archivo /root/server.pub\033[0m"
echo -e "\033[1;33mGuardelo en un lugar seguro, lo necesitará en el futuro!\033[0m"
echo ""
read -p "Presione [Enter] para volver al menu o CTRL+C para salir"
slowdns
