#!/bin/bash
fun_bar() {
   comando[0]="$1"
   comando[1]="$2"
   (
      [[ -e $HOME/fim ]] && rm $HOME/fim
      ${comando[0]} -y >/dev/null 2>&1
      ${comando[1]} -y >/dev/null 2>&1
      touch $HOME/fim
   ) >/dev/null 2>&1 &
   tput civis
   echo -ne "  \033[1;33mESPERE \033[1;37m- \033[1;33m["
   while true; do
      for ((i = 0; i < 18; i++)); do
         echo -ne "\033[1;31m#"
         sleep 0.1s
      done
      [[ -e $HOME/fim ]] && rm $HOME/fim && break
      echo -e "\033[1;33m]"
      sleep 1s
      tput cuu1
      tput dl1
      echo -ne "  \033[1;33mESPERE \033[1;37m- \033[1;33m["
   done
   echo -e "\033[1;33m]\033[1;37m -\033[1;32m OK !\033[1;37m"
   tput cnorm
}
clear
echo -e "\033[1;33mATENCIÓN AQUI POR FAVOR!\033[0m"
echo ""
echo -e "Al final del proceso será necesario configurar"
echo -e "nuevamente el servicio de SlowDNS, elija la opción"
echo -e "Usar la key actual para restaurar su key anterior"
echo ""
read -p "Presione [ENTER] para continuar o CTRL + C para cancelar"
echo ""
echo -e "   \033[0;36mREMOVIENDO ARCHIVOS ANTIGUOS...\033[0m"
echo ""
fun_remove() {
   rm -rf remove-slow
   wget https://github.com/T3mma/script-with-bot/blob/main/slowdns/remove-slow && chmod +x remove-slow && bash remove-slow
   sleep 2
   rm -rf /bin/slowdns && rm /root/remove-slow
   sleep 2
   rm remove-slow && rm -rf /etc/slowdns
}
fun_bar 'fun_remove'
rm -rf /etc/slowdns
echo ""
echo -e "   \033[0;36mACTUALIZANDO SCRIPT...\033[0m"
echo ""
fun_update() {
   rm -rf install && wget https://github.com/T3mma/script-with-bot/blob/main/slowdns/install && chmod +x install && bash install
}
fun_bar 'fun_update'
sleep 3
echo ""
echo -e "\033[0;36mSLOWDNS ACTUALIZADO CON ÉXITO! [✔]\033[0m"
echo ""
sleep 3
echo -e "Para abrir el menu, use el comando: \033[1;33mslowdns\033[0m"
echo ""
read -p "De [ ENTER ] para liberar la terminal"
echo -e "\033[0m"
